### ISSUE TITLE
`npm run test` fails with a `MODULE_NOT_FOUND` error

### ISSUE THREAD

**Issue by RA80533** [npm/libnpmdiff#4]
```console
$ npm run test

> libnpmdiff@2.0.4 test
> tap test/*.js

Error: Cannot find module './reports/base'
Require stack:
- /[…]/libnpmdiff/node_modules/jackspeak/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at resolveFileName (/[…]/libnpmdiff/node_modules/tap/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/[…]/libnpmdiff/node_modules/tap/node_modules/resolve-from/index.js:31:9)
    at module.exports (/[…]/libnpmdiff/node_modules/tap/node_modules/resolve-from/index.js:34:41)
    at importJSX (/[…]/libnpmdiff/node_modules/tap/node_modules/import-jsx/index.js:24:21)
    at module.exports (/[…]/libnpmdiff/node_modules/tap/node_modules/treport/lib/index.js:13:18)
    at exports.makeReporter (/[…]/libnpmdiff/node_modules/tap/bin/run.js:422:23)
    at runTests (/[…]/libnpmdiff/node_modules/tap/bin/run.js:744:3)
    at mainAsync (/[…]/libnpmdiff/node_modules/tap/bin/run.js:244:5)
    at main (/[…]/libnpmdiff/node_modules/tap/bin/run.js:127:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/[…]/libnpmdiff/node_modules/jackspeak/noop.js'
  ]
}
TAP version 13
1..0
# time=1.554ms
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
```

Updating tap to 15.0.5 (its newest version) solves this.

**Comment by fritzy** [comment]
Tap has been updated and this code has been moved into the CLI as a workspace.

https://github.com/npm/cli/tree/release-next/workspaces/libnpmdiff
